kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc-azure-retain
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed