apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mssql-2017
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-azure-retain
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: mssql
type: Opaque
data:
  SA_PASSWORD: UzBtZXRoaW5nU0BTdHIwbmch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment-2017-ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-2017-ubuntu
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql-2017-ubuntu
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: mssql-2017-ubuntu
          image: 'mcr.microsoft.com/mssql/server:2017-latest'
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql
                  key: SA_PASSWORD
          volumeMounts:
            - name: mssql-system
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-system
          persistentVolumeClaim:
            claimName: pvc-mssql-2017
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-deployment-2017-ubuntu
spec:
  selector:
    app: mssql-2017-ubuntu
  ports:
    - protocol: TCP
      port: 14337
      targetPort: 1433
  type: LoadBalancer


# Reference:
#  https://arunksingh16.medium.com/kubernetes-storage-dynamic-provisioning-70e0fe6f6dc6