# kubectl create secret generic mssql --from-literal=SA_PASSWORD="MyC0m9l&xP@ssw0rd" --namespase
# kubectl create secret generic sql-secrets --from-literal=sapassword="MyC0m9l&xP@ssw0rd" --from-literal=masterkeypassword="MyC0m9l&xP@ssw0rd" --namespace ag1
apiVersion: v1
kind: Secret
metadata:
  name: sql-secrets
  namespace: ag1
type: Opaque
data:
  sapassword: MyC0m9l&xP@ssw0rd
  masterkeypassword: MyC0m9l&xP@ssw0rd
---
apiVersion: v1
kind: Secret
metadata:
  name: mssql
  namespace: ag1
type: Opaque
data:
  SA_PASSWORD: MyC0m9l&xP@ssw0rd
  